version: '3'
services:
  web:
    container_name:  flask_nginx_2
    build:
      context: "./"
      dockerfile: "Dockerfile"
    volumes:
       - ./app:/app
    ports:
      - "8010:80"
    environment:
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
      - 'RUN=flask run --host=0.0.0.0 --port=80'
    command: flask run --host=0.0.0.0 --port=80
  db:
    container_name:  flask_db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'flask_db'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - ./docker-mysql:/docker-entrypoint-initdb.d
    ports:
      - '4410:3306'
    expose:
      - '4410'